version: "3.3"
services:
  app:
    container_name: FluxMesTestAufgabeBackend
    image: derccl/flux_mes_testaufgabe_backend:latest
    restart: always
    ports:
      - "8080"
    links:
      - mongo
  mongo:
    container_name: mongo_db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
    links:
      - app
