version: '2.2'
services:
  testaufgabe:
    image: derccl/flux_mes_testaufgabe_backend:latest
    build:
      dockerfile: Dockerfile
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: traefik_default
